"""add quantity to order_products

Revision ID: 178b2dbf877e
Revises: 8ac24070988a
Create Date: 2026-04-22 19:21:27.784668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '178b2dbf877e'
down_revision: Union[str, Sequence[str], None] = '8ac24070988a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_products', sa.Column('quantity', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_products', 'quantity')